### ISSUE TITLE
Followed tutorial and sound now disabled

### ISSUE THREAD

**Issue by lukalafaye** [nebulakl/cave-audio#1]
Using asus c302a chromebook

Followed the tutorial on Gallium OS and sound got disabled.
Using pavucontrol, I can see that a dummy output was used as playback source: http://i.imgur.com/JwiRPC2.png

Also note that the volume up key does not work anymore.

Here's all I've done so far:
[sound-issues.txt](https://github.com/nebulakl/cave-audio/files/4038680/sound-issues.txt)

I would really appreciate any suggestions about it!

**Comment by lukalafaye** [comment]
I reverted changes from step 6 and rebooted. The sound is still disabled with that dummy output displayed as fallback source.

**Comment by lukalafaye** [comment]
I might install Arch with https://github.com/qntmpkts/chroagh if it helps, let me know what you would do!

**Comment by nebulakl** [comment]
iirc the default kernel in Gallium OS was not patched to load the topology file from ChromeOS last time I tried the OS. Do you mind attaching your `dmesg` output?
Switching to Archlinux will not help, because starting from kernel 5.4 an update to the sound driver broke the audio and I have not found a fix yet.
